### ISSUE TITLE
0.5-snapshot has disappeared from maven central

### ISSUE THREAD

**Issue by froth** [Richard-W/scalacrypt#4]
Hi Richard,

as of some days ago the last 0.5-snapshot has disappeared from maven central. Would it be possible to make a 0.5 release, so that it will stay available?

Greetings,

Fred

**Comment by Richard-W** [comment]
Sorry for the long response time. 0.5 is not ready to be released yet and I am currently unable to allocate time to actually continue work on this.

Before another release is made all the self-written crypto has to be replaced by external and properly vetted code. Be very careful when using this software. As written in the README.md this is not suited for security-critical applications at all.
