### ISSUE TITLE
Having problems building with dependencies?

### ISSUE THREAD

**Issue by sdrafahl** [Richard-W/scalacrypt#6]
I was getting this error after trying to build my project after adding this library to my sbt file.

sbt.librarymanagement.ResolveException: unresolved dependency: xyz.wiedenhoeft#scalacrypt_2.12;0.5-SNAPSHOT: not found

**Comment by richard-w** [comment]
There were no 2.12 builds in the repository. It should be fixed now. Please confirm that it works and close the issue.

**Comment by sdrafahl** [comment]
Looks like it works now.
